### ISSUE TITLE
Update touch method to work with laravel 9

### ISSUE THREAD

**Issue by acgtwentyone** [ivanomatteo/laravel-device-tracking#13]
Hi there,

I think this package should be updated to work with laravel 9.

According to the laravel upgrade guide [The touch Method](https://laravel.com/docs/9.x/upgrade#belongs-to-many-first-or-new) If you were previously overwriting this method, you should update your method signature to reflect this new argument.

```php
public function touch($attribute = null);
```

And because of this i am getting the following error after upgrade laravel from 8 to 9.
![Screenshot 2022-06-10 at 18 18 11](https://user-images.githubusercontent.com/94224806/173136132-00454b5f-8855-4444-9650-e655b7029d1b.png)

**Comment by ivanomatteo** [comment]
fixed, thanks

**Comment by acgtwentyone** [comment]
Ok.
