### ISSUE TITLE
PHP 8.0 Supports

### ISSUE THREAD

**Issue by ghost** [ivanomatteo/laravel-device-tracking#9]
- ivanomatteo/laravel-device-tracking 0.1.8 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - ivanomatteo/laravel-device-tracking 0.1.8 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - Installation request for ivanomatteo/laravel-device-tracking ^0.1.8 -> satisfiable by ivanomatteo/laravel-device-tracking[0.1.8].

**Comment by ivanomatteo** [comment]
added
